### PR TITLE
Refcount-based fix for index memory releasing problem

### PR DESCRIPTION
**Pull request by jmarshall**
On #67, I wrote

> It would probably be possible to add a reference to the Bio::DB::HTSfile to the Bio::DB::HTS::Index object to get the objects destroyed in the right order. Either in the XS code (non-trivial) or in the Perl wrappers (hopefully easier).

This implements that. First attempt was via `sv_magic()`, but that didn't get the ordering right. Using an external global hash is a bit more manual but also more explicit.

### CODE REVIEW

**Comment by avullo** [comment]
That's very nice @jmarshall, I couldn't think of a better way of solving this. I guess you've checked with environment which was causing you problems (5.10.1) and it didn't show problems running it multiple times.

**Comment by jmarshall** [comment]
Yes, with this change there's no valgrind _invalid read_ errors on Perl 5.10.1 for _t/03cram.t_. Across many runs.

`valgrind ./Build test` completes without problems too.

**Comment by avullo** [comment]
Brilliant, getting this in

**Comment by jmarshall** [comment]
Thanks!

**Comment by avullo** [comment]
:+1: :+1:

**Pull request merged**
